#!/bin/sh
# Embed the IOP modules the streaming bench needs into the ELF.
#
# WHY THE ELF HAS TO CARRY THEM. The first sitting reported
# `src: SYNTHETIC (open cover0: -1)` from a stick whose files were
# verified byte-exact. The cause is not the drive: wLaunchELF launches
# via LoadExecPS2, which RESETS THE IOP, so every USB driver the
# launcher had loaded for its own file browser is gone before our
# first instruction runs. The assumption that a USB-capable launcher
# leaves them resident was simply wrong, and it was the one thing in
# the bench PR that CI could compile but not test.
#
# WHY THIS IS A SCRIPT AND NOT A MAKEFILE RULE. Which modules exist
# depends on the PS2SDK vintage. Modern SDKs ship the BDM stack
# (bdm + bdmfs_fatfs + usbmass_bd); older ones ship usbhdfsd. Both
# present `mass:`. Rather than pin one and break on the other, this
# looks, picks whichever set is COMPLETE, and records which -- and if
# neither is, it emits an empty table so the ELF says "no modules
# embedded" on screen instead of failing to link with a name nobody
# at a bench can act on.
set -e
out="${1:-.}"
irx="${PS2SDK}/iop/irx"
bin2c="${PS2SDK}/bin/bin2c"

# Ordered. usbd first in both: the mass drivers bind to it.
BDM="usbd bdm bdmfs_fatfs usbmass_bd"
LEGACY="usbd usbhdfsd"

have_all() {
    for m in $1; do [ -f "$irx/$m.irx" ] || return 1; done
    return 0
}

if have_all "$BDM"; then
    SET="$BDM"; WHICH="bdm"
elif have_all "$LEGACY"; then
    SET="$LEGACY"; WHICH="legacy"
else
    SET=""; WHICH="none"
fi

echo "embed_irx: $WHICH stack: ${SET:-<nothing found in $irx>}" >&2

# ONE generated .c, with the module bytes inlined rather than left in
# per-module files. The first version emitted irx_<name>.c each and
# collected them with $(wildcard) in the Makefile -- which evaluates
# when make PARSES the file, before this script has run, so on a clean
# tree the wildcard matched nothing and the modules were silently left
# out of the link. A generated file list cannot be discovered by the
# same make pass that generates it.
{
    echo '/* Generated by embed_irx.sh. Do not edit. */'
    echo '#include "irx_table.h"'
    echo
} > "$out/irx_table.c"

for m in $SET; do
    "$bin2c" "$irx/$m.irx" "$out/irx_tmp_$m.c" "irx_$m"
    cat "$out/irx_tmp_$m.c" >> "$out/irx_table.c"
    rm -f "$out/irx_tmp_$m.c"
done

{
    echo
    echo "const irx_module irx_modules[] = {"
    for m in $SET; do
        echo "    { \"$m\", irx_$m, &size_irx_$m },"
    done
    echo "};"
    echo "const int n_irx_modules = sizeof irx_modules / sizeof irx_modules[0];"
    echo "const char *const irx_stack_name = \"$WHICH\";"
} >> "$out/irx_table.c"

cat > "$out/irx_table.h" <<'HDR'
/* Generated by embed_irx.sh. Do not edit. */
#ifndef PS2UI_IRX_TABLE_H
#define PS2UI_IRX_TABLE_H

typedef struct irx_module {
    const char          *name;   /* for the on-screen failure line */
    unsigned char       *buf;
    const unsigned int  *size;
} irx_module;

extern const irx_module   irx_modules[];
extern const int          n_irx_modules;
extern const char *const  irx_stack_name;

#endif
HDR
