/* Standalone PS2 sample: boots, loads the embedded .uib, replays it,
 * and cycles focus through every node so an emulator screenshot run
 * covers each state. This is the ELF the hardware bring-up checklist
 * (docs/bringup.md) and the CI emulator job drive.
 *
 * Build with the PS2SDK toolchain (see Makefile); the blob is embedded
 * at build time via bin2c, so the ELF is self-contained — no host or
 * memory-card I/O involved in bring-up.
 */

#include <kernel.h>
#include <gsKit.h>
#include <dmaKit.h>

#include "../ps2ui.h"

/* Generated by bin2c from the baked example blob. */
extern unsigned char ui_uib[];
extern unsigned int size_ui_uib;

/* Frames to hold each focus state — long enough for a screenshot. */
#define FRAMES_PER_STATE 150

int main(void)
{
    GSGLOBAL *gs;
    ps2ui_ctx ui;
    int rc;
    unsigned frame = 0;

    dmaKit_init(D_CTRL_RELE_OFF, D_CTRL_MFD_OFF, D_CTRL_STS_UNSPEC,
                D_CTRL_STD_OFF, D_CTRL_RCYC_8, 1 << DMA_CHANNEL_GIF);
    dmaKit_chan_init(DMA_CHANNEL_GIF);

    gs = gsKit_init_global();
    gs->PSM = GS_PSM_CT32;
    gs->PSMZ = GS_PSMZ_16S;
    gs->DoubleBuffering = GS_SETTING_ON;
    gs->ZBuffering = GS_SETTING_OFF; /* strict back-to-front paint order */
    gsKit_init_screen(gs);
    gsKit_mode_switch(gs, GS_ONESHOT);

    /* ps2ui blobs carry GS-domain alpha; the standard blend equation
     * (Cs - Cd) * As >> 7 + Cd is exactly what the baker assumed. */
    gs->PrimAlphaEnable = GS_SETTING_ON;

    rc = ps2ui_load(&ui, ui_uib, size_ui_uib);
    if (rc != PS2UI_OK) {
        /* Bring-up step 1 failure: solid red = load error. */
        while (1) {
            gsKit_clear(gs, GS_SETREG_RGBAQ(0x80, 0x00, 0x00, 0x80, 0x00));
            gsKit_queue_exec(gs);
            gsKit_sync_flip(gs);
        }
    }
    if (ps2ui_upload(&ui, gs) != 0) {
        /* Solid yellow = VRAM alloc failure (bring-up step 9). */
        while (1) {
            gsKit_clear(gs, GS_SETREG_RGBAQ(0x80, 0x80, 0x00, 0x80, 0x00));
            gsKit_queue_exec(gs);
            gsKit_sync_flip(gs);
        }
    }

    while (1) {
        /* Canvas background: #0a0e1a in flat-shaded full-range RGB. */
        gsKit_clear(gs, GS_SETREG_RGBAQ(0x0a, 0x0e, 0x1a, 0x80, 0x00));
        ps2ui_render(&ui, gs);
        gsKit_queue_exec(gs);
        gsKit_sync_flip(gs);

        /* Walk every focus state so a timed screenshot sweep sees each
         * one: hold, then move right (wrapping via down) through the
         * graph; when movement dead-ends, jump back to the initial. */
        frame++;
        if (frame % FRAMES_PER_STATE == 0) {
            if (!ps2ui_move(&ui, PS2UI_RIGHT) && !ps2ui_move(&ui, PS2UI_DOWN))
                ui.focus = ui.hdr->initial_focus;
        }
    }
    return 0;
}
