/* Standalone PS2 sample: boots, loads the embedded .uib, replays it,
 * and cycles focus through every node so an emulator screenshot run
 * covers each state. This is the ELF the hardware bring-up checklist
 * (docs/bringup.md) and the CI emulator job drive.
 *
 * Build with the PS2SDK toolchain (see Makefile); the blob is embedded
 * at build time via bin2c, so the ELF is self-contained — no host or
 * memory-card I/O involved in bring-up.
 */

#include <kernel.h>
#include <gsKit.h>
#include <dmaKit.h>

#include "../ps2ui.h"

/* Generated by bin2c from the baked example blob. */
extern unsigned char ui_uib[];
extern unsigned int size_ui_uib;

/* Frames to hold each focus state — long enough for a screenshot. */
#define FRAMES_PER_STATE 150

/* Build with -DPS2UI_SAMPLE_STATIC to hold the baked initial focus
 * forever instead of walking the graph.
 *
 * Cycling is what you want when a person is watching, and exactly what
 * you cannot have when a machine is diffing: an automated capture lands
 * at whatever wall-clock moment the screenshot fires, so the frame it
 * grabs is not the frame `--preview` rendered, and the comparison is
 * non-deterministic by construction. The CI emulator job builds with
 * this defined; docs/bringup.md drives the cycling build by hand. */
#ifdef PS2UI_SAMPLE_STATIC
#define PS2UI_SAMPLE_CYCLE 0
#else
#define PS2UI_SAMPLE_CYCLE 1
#endif

#ifdef PS2UI_SAMPLE_PROBE
/* Bring-up step 2 as a program, for when solid fills do not appear.
 *
 * The first emulator capture came back 92.8% pure black with every text
 * colour present and correct to within one unit. So textured sprites
 * work — atlas, CLUT, CSM1 swizzle, modulate domain, all of it — and
 * nothing untextured drew at all, including `gsKit_clear`, which is not
 * ps2ui's code. That narrows the fault to solid sprites, and leaves
 * four candidates it cannot separate: the clear, blending-off sprites,
 * blending-on opaque sprites, and blending-on translucent sprites.
 *
 * This draws one of each in a colour that appears nowhere in either
 * example, so `framediff --stats` names exactly which survived. No
 * .uib is involved: if this frame is wrong, ps2ui is not why.
 *
 *   ground  #0a0e1a   gsKit_clear, blending off
 *   red     #ff0000   sprite, blending off
 *   green   #00ff00   sprite, blending on, alpha 0x80 (GS opaque)
 *   blue    #0000ff   sprite, blending on, alpha 0x40 (half)
 *
 * A half-alpha blue over the dark ground composites to about #05070d,
 * so blue at full strength means the blend unit ignored alpha, and no
 * blue at all means translucent sprites are dropped. Each quadrant is
 * 200x160, roughly 16% of the frame, far above the noise in a palette
 * listing. */
static void probe_frame(GSGLOBAL *gs)
{
    gs->PrimAlphaEnable = GS_SETTING_OFF;
    gsKit_clear(gs, GS_SETREG_RGBAQ(0x0a, 0x0e, 0x1a, 0x80, 0x00));

    gsKit_prim_sprite(gs, 40.0f, 40.0f, 240.0f, 200.0f, 0,
                      GS_SETREG_RGBAQ(0xff, 0x00, 0x00, 0x80, 0x00));

    gs->PrimAlphaEnable = GS_SETTING_ON;
    gsKit_prim_sprite(gs, 400.0f, 40.0f, 600.0f, 200.0f, 0,
                      GS_SETREG_RGBAQ(0x00, 0xff, 0x00, 0x80, 0x00));
    gsKit_prim_sprite(gs, 40.0f, 248.0f, 240.0f, 408.0f, 0,
                      GS_SETREG_RGBAQ(0x00, 0x00, 0xff, 0x40, 0x00));
}
#endif

int main(void)
{
    GSGLOBAL *gs;
    ps2ui_ctx ui;
    int rc;
    unsigned frame = 0;

    dmaKit_init(D_CTRL_RELE_OFF, D_CTRL_MFD_OFF, D_CTRL_STS_UNSPEC,
                D_CTRL_STD_OFF, D_CTRL_RCYC_8, 1 << DMA_CHANNEL_GIF);
    dmaKit_chan_init(DMA_CHANNEL_GIF);

    gs = gsKit_init_global();
    gs->PSM = GS_PSM_CT32;
    gs->PSMZ = GS_PSMZ_16S;
    gs->DoubleBuffering = GS_SETTING_ON;
    gs->ZBuffering = GS_SETTING_OFF; /* strict back-to-front paint order */
    gsKit_init_screen(gs);
    gsKit_mode_switch(gs, GS_ONESHOT);

    /* ps2ui blobs carry GS-domain alpha; the standard blend equation
     * (Cs - Cd) * As >> 7 + Cd is exactly what the baker assumed. */
    gs->PrimAlphaEnable = GS_SETTING_ON;

#ifdef PS2UI_SAMPLE_PROBE
    /* No blob, no ps2ui: just the four primitive cases. */
    while (1) {
        probe_frame(gs);
        gsKit_queue_exec(gs);
        gsKit_sync_flip(gs);
    }
#endif

    rc = ps2ui_load(&ui, ui_uib, size_ui_uib);
    if (rc != PS2UI_OK) {
        /* Bring-up step 1 failure: solid red = load error. */
        while (1) {
            gsKit_clear(gs, GS_SETREG_RGBAQ(0x80, 0x00, 0x00, 0x80, 0x00));
            gsKit_queue_exec(gs);
            gsKit_sync_flip(gs);
        }
    }
    if (ps2ui_upload(&ui, gs) != 0) {
        /* Solid yellow = VRAM alloc failure (bring-up step 9). */
        while (1) {
            gsKit_clear(gs, GS_SETREG_RGBAQ(0x80, 0x80, 0x00, 0x80, 0x00));
            gsKit_queue_exec(gs);
            gsKit_sync_flip(gs);
        }
    }

    while (1) {
        /* Canvas background: #0a0e1a in flat-shaded full-range RGB. */
        gsKit_clear(gs, GS_SETREG_RGBAQ(0x0a, 0x0e, 0x1a, 0x80, 0x00));
        ps2ui_render(&ui, gs);
        gsKit_queue_exec(gs);
        gsKit_sync_flip(gs);

        /* Walk every focus state so a timed screenshot sweep sees each
         * one: hold, then move right (wrapping via down) through the
         * graph; when movement dead-ends, jump back to the initial. */
        frame++;
        if (PS2UI_SAMPLE_CYCLE && frame % FRAMES_PER_STATE == 0) {
            if (!ps2ui_move(&ui, PS2UI_RIGHT) && !ps2ui_move(&ui, PS2UI_DOWN))
                ui.focus = ui.hdr->initial_focus;
        }
    }
    return 0;
}
