/* Standalone PS2 sample: boots, loads the embedded .uib, replays it,
 * and cycles focus through every node so an emulator screenshot run
 * covers each state. This is the ELF the hardware bring-up checklist
 * (docs/bringup.md) and the CI emulator job drive.
 *
 * Build with the PS2SDK toolchain (see Makefile); the blob is embedded
 * at build time via bin2c, so the ELF is self-contained — no host or
 * memory-card I/O involved in bring-up.
 */

#include <kernel.h>
#include <stdio.h>
#include <gsKit.h>
#include <dmaKit.h>

#include "../ps2ui.h"

/* Generated by bin2c from the baked example blob. */
extern unsigned char ui_uib[];
extern unsigned int size_ui_uib;

/* Frames to hold each focus state — long enough for a screenshot. */
#define FRAMES_PER_STATE 150

/* How long the probe holds its screen before returning to the browser.
 * Long enough to look at it and photograph it; short enough that an
 * operator is not left wondering. */
#define PROBE_FRAMES (90u * 60u)   /* ~90 s NTSC, ~108 s PAL */

/* `make MINIMAL=1` builds bring-up step 1 and nothing else: clear the
 * screen, hold, exit. Three gsKit calls, no sprites, no blending, no
 * textures, no blob.
 *
 * It exists so the first thing that ever touches a console is the
 * smallest surface that can prove anything. If it works, then the ELF
 * loads and boots, dmaKit and gsKit init, the video mode is accepted,
 * the framebuffer flips, and returning from main gets back to the
 * browser -- all confirmed before a single primitive is submitted.
 * Step 2 then adds exactly one thing. A probe that draws everything at
 * once cannot tell you which half failed.
 *
 * The colour is chosen so it also tests channel order for free: R, G
 * and B are 0x40, 0x80, 0xc0, strictly increasing, so a correct frame
 * is unmistakably BLUE and a byte-swapped one is unmistakably ORANGE.
 * "Wrong colours entirely" is a documented step 2 failure mode; this
 * catches it a step earlier and without ambiguity. */
#define MINIMAL_FRAMES (30u * 60u) /* ~30 s NTSC, ~36 s PAL */

/* Build with -DPS2UI_SAMPLE_TELEMETRY for a once-a-second log line on
 * stdout. printf from the EE reaches PCSX2's console log, ps2link, and
 * any TTY hook — no IRX modules, no storage, nothing to mount, which
 * is why this is the first sink rather than USB or UDP: it works on
 * the very first boot, before anything else is proven.
 *
 * The line is machine-fixed and grep-friendly:
 *
 *   ps2ui-telemetry frame=300 fps=60.0 miss=0 ee_us(min/avg/max)=412/430/501
 *       prims=375 hidden=0 slotg=42 slothid=0 sciov=0
 *
 * fps is measured from elapsed wall-clock cycles, not derived from the
 * miss count: a UI running steadily at half rate overruns a field on
 * every frame, so `60 - missed` would report 0 fps for a program
 * rendering perfectly well at 30. They are independent signals and the
 * interval is a real second either way.
 *
 * ee_us is ps2ui_render alone (composition cost, not GPU), measured
 * with the EE's COP0 cycle counter. miss counts frames where the whole
 * loop overran one 60 Hz field.
 *
 * The ps2ui counters are aggregated across the interval, not sampled
 * from its last frame. sciov especially: a nonzero value means a blob
 * deeper than PS2UI_MAX_SCISSOR_DEPTH reached the console, and B16's
 * lesson was that this condition is silent and remote from its cause —
 * sampling it at a 1-in-60 duty cycle would keep it silent 98% of the
 * time. prims/slotg report the interval's peak, which is the number
 * that matters for budgeting.
 */
#ifdef PS2UI_SAMPLE_TELEMETRY
/* COP0 Count on the R5900 ticks once per CPU cycle at 294.912 MHz.
 * TODO(bench): confirm on hardware. Several MIPS implementations tick
 * Count at half the core clock, and if the R5900 is one of them every
 * ee_us here is 2x off. The bench session settles it: render a known
 * fixed workload and compare ee_us against a stopwatch over 600
 * frames. Until then treat ee_us as relative, not absolute. */
#define EE_HZ 294912000u
static inline u32 cop0_count(void)
{
    u32 v;
    /* __asm__ __volatile__, not `asm volatile`: the sample builds
     * -std=c99, which is strict ISO C where `asm` is not a keyword —
     * GCC only spells it that way in the gnu* dialects. The
     * underscored form is available in every mode. */
    __asm__ __volatile__("mfc0 %0, $9" : "=r"(v));
    return v;
}
#endif

/* Build with -DPS2UI_SAMPLE_STATIC to hold the baked initial focus
 * forever instead of walking the graph.
 *
 * Cycling is what you want when a person is watching, and exactly what
 * you cannot have when a machine is diffing: an automated capture lands
 * at whatever wall-clock moment the screenshot fires, so the frame it
 * grabs is not the frame `--preview` rendered, and the comparison is
 * non-deterministic by construction. The CI emulator job builds with
 * this defined; docs/bringup.md drives the cycling build by hand. */
#ifdef PS2UI_SAMPLE_STATIC
#define PS2UI_SAMPLE_CYCLE 0
#else
#define PS2UI_SAMPLE_CYCLE 1
#endif

#ifdef PS2UI_SAMPLE_PROBE
/* Bring-up step 2 as a program: which primitive paths reach the screen,
 * and does the GS blend the way the baker assumed.
 *
 * HARDWARE, SCPH-50000, first run: the clear, the unblended control and
 * the blended ladder all drew, and the ELF returned to the browser on
 * its own. So GIF encoding, both packet forms, ABE and the blend unit
 * are all live on real silicon -- that much is settled and this probe
 * is no longer asking it. What the first run could NOT settle was the
 * ladder itself; see the v2 note above probe_frame for why, and what
 * changed.
 *
 * The first emulator capture came back 92.8% pure black with every text
 * colour present and correct to within one unit. So the textured path
 * works — atlas, CLUT, CSM1 swizzle, modulate domain — and nothing
 * untextured drew, including `gsKit_clear`, which is not ps2ui's code.
 *
 * What this actually separates is GIF packet encoding, then blending,
 * then the alpha value, which is a sharper instrument than "the clear
 * versus sprites" suggests:
 *
 *   - `gsKit_clear` does not go through `gsKit_prim_sprite`. It builds
 *     a PACKED A+D list via `gsKit_prim_list_sprite_flat`, while
 *     `gsKit_prim_sprite` emits a sprite GIF tag with SPRITE_REGS.
 *     Those are two different packet encodings, and an emulator can
 *     implement one and not the other.
 *   - then ABE off versus on,
 *   - then the alpha value itself, across the ladder below.
 *
 * The ground colour is deliberately not any example's: #1a0e0a is the
 * memcard canvas #0a0e1a with its channels reversed, so a fingerprint
 * cannot be confused with a UI capture in the same log.
 *
 * NOTE: current gsKit does *not* save and restore PrimAlphaEnable
 * around `gsKit_clear` (older versions did). The explicit disable below
 * is load-bearing, not redundant — do not tidy it away. It also means
 * the shipping render loop, which clears with ABE on at alpha 0x80,
 * differs from this probe in exactly the variable under test; if step 2
 * reads clean and the UI still does not, flip that first.
 *
 * A `.uib` is still linked into this ELF (bin2c runs regardless), so a
 * baked blob must exist to build it. Nothing draws it. */
/* HARDWARE RESULT, v2, SCPH-50000: columns 1, 2, 3 and 6 painted both
 * halves; columns 4 and 5 -- alpha 0x7f and 0x80 -- painted the
 * reference and NOTHING in the test half. Play! did the same thing.
 *
 * Two independent GS implementations agreeing points at this tree, not
 * at silicon, and the grep that follows is damning: nothing in
 * runtime/ or sample/ has ever written the GS ALPHA register, the TEST
 * register or PABE. Every one of them is whatever gsKit_init_screen
 * happened to leave behind, while the baker computes alpha in the
 * 0..128 domain on the assumption that the blend is
 * (Cs - Cd) * As >> 7 + Cd with C selecting As. Nothing asserted that.
 *
 * Note what rules the obvious suspect out. The reference swatches carry
 * vertex alpha 0x80 too, and column 5's reference drew perfectly. An
 * alpha test rejecting high alpha would have taken it with the others.
 * The only difference between a reference that draws and a test that
 * vanishes is ABE, so the fault is in the blend, not in a discard.
 *
 * v3 therefore draws the ladder TWICE: once on inherited state, once
 * with the blend registers set explicitly. Top ladder seamed and
 * bottom ladder clean isolates it to the state and hands over the fix.
 * If both read alike, gsKit applies this state at queue-exec rather
 * than per primitive, which is worth knowing too and is why the
 * comment above gsKit_clear already warns about PrimAlphaEnable. */
static const unsigned char probe_ref_alpha[]  = { 0x20, 0x40, 0x60, 0x7f, 0x80, 0x80 };
static const unsigned char probe_test_alpha[] = { 0x20, 0x40, 0x60, 0x7f, 0x80, 0x20 };
#define PROBE_COLUMNS 6

#define PROBE_GND_R 0x1a
#define PROBE_GND_G 0x0e
#define PROBE_GND_B 0x0a

/* Not full magenta any more. Measuring the v2 photographs channel by
 * channel showed the panel and camera together clip hard: references
 * of #8c0784, #c503c1, #fd00fd and #ff00ff all came back within ten
 * units of each other, so the top two thirds of the ladder were
 * unreadable in absolute terms and the v2 calibration column -- a
 * #c503c1 against a #8c0784 -- compressed into a false "seamless".
 * A source that peaks at 0x90 keeps every rung inside the range the
 * camera still resolves. The blend is linear in Cs, so testing at 0x90
 * tests exactly what testing at 0xff would, and can be read. */
#define PROBE_SRC_R 0x90
#define PROBE_SRC_G 0x00
#define PROBE_SRC_B 0x90

#define PROBE_SAFE_X0 64
#define PROBE_SAFE_Y0 45
#define PROBE_SAFE_X1 576
#define PROBE_SAFE_Y1 403

static int probe_blend(int cs, int cd, int as)
{
    int v = (((cs - cd) * as) >> 7) + cd;
    if (v < 0) v = 0;
    if (v > 255) v = 255;
    return v;
}

static void probe_bracket(GSGLOBAL *gs, int cx, int cy, int dx, int dy,
                          int arm, int thick, u64 colour)
{
    float x0 = (float)(dx > 0 ? cx : cx - arm);
    float x1 = (float)(dx > 0 ? cx + arm : cx);
    float y0 = (float)(dy > 0 ? cy : cy - thick);
    float y1 = (float)(dy > 0 ? cy + thick : cy);
    gsKit_prim_sprite(gs, x0, y0, x1, y1, 0, colour);

    x0 = (float)(dx > 0 ? cx : cx - thick);
    x1 = (float)(dx > 0 ? cx + thick : cx);
    y0 = (float)(dy > 0 ? cy : cy - arm);
    y1 = (float)(dy > 0 ? cy + arm : cy);
    gsKit_prim_sprite(gs, x0, y0, x1, y1, 0, colour);
}

/* Geometry lives in macros so the #if guards below check the layout
 * rather than a hand-copied model of it. The v2 probe ran outside the
 * safe box; a guard that re-derives the columns from its own literals
 * would go stale the moment someone edits the array, which is the same
 * mistake one level up. */
#define PROBE_COL_X0 72
#define PROBE_COL_DX 85
#define PROBE_COL_W  70
#define PROBE_TICK_DX 12
#define PROBE_TICK_W  8
#define PROBE_TOP_Y   52
#define PROBE_BOT_Y   398
static const int probe_col_x[PROBE_COLUMNS] = {
    PROBE_COL_X0 + 0 * PROBE_COL_DX, PROBE_COL_X0 + 1 * PROBE_COL_DX,
    PROBE_COL_X0 + 2 * PROBE_COL_DX, PROBE_COL_X0 + 3 * PROBE_COL_DX,
    PROBE_COL_X0 + 4 * PROBE_COL_DX, PROBE_COL_X0 + 5 * PROBE_COL_DX
};

/* One ladder: the colour the blend equation predicts, laid down
 * literally with blending off, sitting directly on top of what the
 * blend actually produces. Match and the column is one rectangle;
 * mismatch and there is a seam, which survives any exposure, white
 * balance or angle in a way that naming a colour does not. */
static void probe_ladder(GSGLOBAL *gs, float ytop, float ymid, float ybot)
{
    int i;

    gs->PrimAlphaEnable = GS_SETTING_OFF;
    for (i = 0; i < PROBE_COLUMNS; i++) {
        int as = probe_ref_alpha[i];
        int r = probe_blend(PROBE_SRC_R, PROBE_GND_R, as);
        int g = probe_blend(PROBE_SRC_G, PROBE_GND_G, as);
        int b = probe_blend(PROBE_SRC_B, PROBE_GND_B, as);
        gsKit_prim_sprite(gs, (float)probe_col_x[i], ytop,
                          (float)(probe_col_x[i] + PROBE_COL_W), ymid, 0,
                          GS_SETREG_RGBAQ(r, g, b, 0x80, 0x00));
    }

    gs->PrimAlphaEnable = GS_SETTING_ON;
    for (i = 0; i < PROBE_COLUMNS; i++) {
        gsKit_prim_sprite(gs, (float)probe_col_x[i], ymid,
                          (float)(probe_col_x[i] + PROBE_COL_W), ybot, 0,
                          GS_SETREG_RGBAQ(PROBE_SRC_R, PROBE_SRC_G, PROBE_SRC_B,
                                          probe_test_alpha[i], 0x00));
    }
}

/* Column 6 is the calibration: its reference is computed for 0x80 while
 * its test is drawn at 0x20, so it MUST seam in both ladders. Without
 * it "no seam" is unfalsifiable -- it could equally mean nothing here
 * resolves a seam. v2 proved that is not a theoretical worry: its
 * calibration pair was #c503c1 against #8c0784, the camera flattened
 * both to the same value, and the column read clean when it was
 * supposed to be the one thing that could not. The mismatch is now
 * large and in the dark direction, where the response still has range. */
#if (PROBE_COL_X0 + PROBE_COL_DX * (PROBE_COLUMNS - 1) + PROBE_COL_W) > PROBE_SAFE_X1
#error "probe ladder runs past the title-safe box"
#endif
#if (PROBE_COL_X0 + PROBE_COL_DX * (PROBE_COLUMNS - 1) \
     + PROBE_TICK_DX * (PROBE_COLUMNS - 1) + PROBE_TICK_W) > PROBE_SAFE_X1
#error "probe tick marks run past the title-safe box"
#endif
#if PROBE_COL_DX < PROBE_COL_W
#error "probe columns overlap; a seam between neighbours is not a seam within one"
#endif
#if PROBE_COL_X0 < PROBE_SAFE_X0 || PROBE_BOT_Y > PROBE_SAFE_Y1 \
    || PROBE_TOP_Y < PROBE_SAFE_Y0
#error "probe content runs outside the title-safe box"
#endif

/* gsKit's ALPHA default, latched before anything overwrites it. Read
 * once from the first probe_frame call rather than at init so it is
 * captured after gsKit_init_screen has had its say. */
static u64 probe_inherited_alpha;
static int probe_latched;

static void probe_frame(GSGLOBAL *gs)
{
    int i, t;

    if (!probe_latched) {
        probe_inherited_alpha = gs->PrimAlpha;
        probe_latched = 1;
    }

    gs->PrimAlphaEnable = GS_SETTING_OFF;
    gsKit_clear(gs, GS_SETREG_RGBAQ(PROBE_GND_R, PROBE_GND_G,
                                    PROBE_GND_B, 0x80, 0x00));

    /* White on the true frame edge, cyan on the title-safe box. Both
     * rings means no overscan; cyan alone means the panel eats the
     * edges but every swatch is still inside and the reading stands;
     * neither means fix the display before believing anything. */
    for (i = 0; i < 4; i++) {
        int dx = (i & 1) ? -1 : 1;
        int dy = (i & 2) ? -1 : 1;
        probe_bracket(gs, (i & 1) ? 640 : 0, (i & 2) ? 448 : 0, dx, dy,
                      64, 6, GS_SETREG_RGBAQ(0xff, 0xff, 0xff, 0x80, 0x00));
        probe_bracket(gs, (i & 1) ? PROBE_SAFE_X1 : PROBE_SAFE_X0,
                      (i & 2) ? PROBE_SAFE_Y1 : PROBE_SAFE_Y0, dx, dy,
                      48, 6, GS_SETREG_RGBAQ(0x00, 0xff, 0xff, 0x80, 0x00));
    }

    /* Controls: unblended, primary and full white. Red alone cannot
     * distinguish "green and blue are dead" from "red is correct". */
    gsKit_prim_sprite(gs, (float)PROBE_COL_X0, (float)PROBE_TOP_Y,
                      (float)PROBE_COL_X0 + 160.0f, (float)PROBE_TOP_Y + 60.0f, 0,
                      GS_SETREG_RGBAQ(0xff, 0x00, 0x00, 0x80, 0x00));
    gsKit_prim_sprite(gs, 272.0f, 52.0f, 432.0f, 112.0f, 0,
                      GS_SETREG_RGBAQ(0xff, 0xff, 0xff, 0x80, 0x00));

    /* Column numbers: i+1 ticks over column i, so a column that sinks
     * into the ground is named by the gap rather than inferred from the
     * width of its neighbours. They also pin the orientation: reading
     * 1..6 left to right is what proved the v2 rectification honest. */
    for (i = 0; i < PROBE_COLUMNS; i++) {
        for (t = 0; t <= i; t++) {
            float x = (float)(probe_col_x[i] + t * PROBE_TICK_DX);
            gsKit_prim_sprite(gs, x, 124.0f, x + (float)PROBE_TICK_W, 136.0f, 0,
                              GS_SETREG_RGBAQ(0xff, 0xff, 0xff, 0x80, 0x00));
        }
    }

    /* Upper ladder: gsKit's default blend, restored explicitly.
     *
     * Drawing it on "whatever state is current" looked equivalent and
     * was not. probe_frame runs every frame, so the set_primalpha at
     * the bottom of this function persists into the next one and from
     * frame two onward the upper ladder inherits the FIXED state. A
     * capture twenty seconds in showed both ladders clean and the A/B
     * silently measuring nothing.
     *
     * The default is latched once at startup, before anything writes
     * it, so the comparison stays a comparison on every frame. Same
     * hazard as the PrimAlphaEnable note above gsKit_clear, and the
     * same reason ps2ui_render re-asserts the equation per frame
     * rather than once at init. */
    gsKit_set_primalpha(gs, probe_inherited_alpha, 0);
    probe_ladder(gs, 148.0f, 206.0f, 264.0f);

    /* Lower ladder: the same draw calls with the blend spelled out.
     *
     *   ALPHA = (Cs - Cd) * As >> 7 + Cd   -- A=Cs B=Cd C=As D=Cd
     *   PABE  = 0                          -- blend every pixel, not
     *                                         only those with As bit 7
     *   TEST  = alpha test off             -- nothing discarded
     *
     * Through gsKit_set_primalpha, not by assigning gs->PrimAlpha:
     * the field is not what emits the register. v3 assigned it, the
     * lower ladder came back byte-identical to the upper one, and that
     * silence is what identified the call.
     *
     * This is the equation docs/format-uib.md says the file's alpha
     * domain assumes. Asserting it here is the point: if the lower
     * ladder is clean where the upper one seams, the shipping runtime
     * needs these three lines too. */
    gsKit_set_primalpha(gs, GS_SETREG_ALPHA(0, 1, 0, 1, 0), 0);
    gsKit_set_test(gs, GS_ATEST_OFF);
    probe_ladder(gs, 282.0f, 340.0f, (float)PROBE_BOT_Y);
}
#endif

int main(void)
{
    GSGLOBAL *gs;
    ps2ui_ctx ui;
    int rc;
    unsigned frame = 0;

    dmaKit_init(D_CTRL_RELE_OFF, D_CTRL_MFD_OFF, D_CTRL_STS_UNSPEC,
                D_CTRL_STD_OFF, D_CTRL_RCYC_8, 1 << DMA_CHANNEL_GIF);
    dmaKit_chan_init(DMA_CHANNEL_GIF);

    gs = gsKit_init_global();
    gs->PSM = GS_PSM_CT32;
    gs->PSMZ = GS_PSMZ_16S;
    gs->DoubleBuffering = GS_SETTING_ON;
    gs->ZBuffering = GS_SETTING_OFF; /* strict back-to-front paint order */
    gsKit_init_screen(gs);
    gsKit_mode_switch(gs, GS_ONESHOT);

    /* ps2ui blobs carry GS-domain alpha; the standard blend equation
     * (Cs - Cd) * As >> 7 + Cd is exactly what the baker assumed. */
    gs->PrimAlphaEnable = GS_SETTING_ON;

#ifdef PS2UI_SAMPLE_MINIMAL
    /* Bring-up step 1: does anything at all reach the screen? */
    for (frame = 0; frame < MINIMAL_FRAMES; frame++) {
        gsKit_clear(gs, GS_SETREG_RGBAQ(0x40, 0x80, 0xc0, 0x80, 0x00));
        gsKit_queue_exec(gs);
        gsKit_sync_flip(gs);
    }
    return 0;
#endif

#ifdef PS2UI_SAMPLE_PROBE
    /* No blob, no ps2ui: just the four primitive cases.
     *
     * Bounded, not `while (1)`. A frozen console and a working one look
     * identical on a static screen, so an unbounded loop makes the
     * operator guess -- and guessing wrong costs a bench session. After
     * PROBE_SECONDS it returns to the browser, which turns "did it
     * work?" into an observation:
     *
     *   picture, then back at the FMCB menu  -> ran to completion
     *   picture, but never returns           -> hung after drawing
     *   no picture, never returns            -> hung before drawing
     *   no picture, but returns              -> ran; the GS drew nothing
     *
     * Two of those four were indistinguishable before. */
    for (frame = 0; frame < PROBE_FRAMES; frame++) {
        probe_frame(gs);
        gsKit_queue_exec(gs);
        gsKit_sync_flip(gs);
    }
    return 0;
#endif

    rc = ps2ui_load(&ui, ui_uib, size_ui_uib);
    if (rc != PS2UI_OK) {
        /* Bring-up step 1 failure: solid red = load error. */
        while (1) {
            gsKit_clear(gs, GS_SETREG_RGBAQ(0x80, 0x00, 0x00, 0x80, 0x00));
            gsKit_queue_exec(gs);
            gsKit_sync_flip(gs);
        }
    }
    if (ps2ui_upload(&ui, gs) != 0) {
        /* Solid yellow = VRAM alloc failure (bring-up step 9). */
        while (1) {
            gsKit_clear(gs, GS_SETREG_RGBAQ(0x80, 0x80, 0x00, 0x80, 0x00));
            gsKit_queue_exec(gs);
            gsKit_sync_flip(gs);
        }
    }

#ifdef PS2UI_SAMPLE_TELEMETRY
    u32 t_min = 0xFFFFFFFFu, t_max = 0, t_sum = 0;
    u32 sec_frames = 0, missed = 0, t_frame_prev = cop0_count();
    u32 elapsed = 0;
    /* Interval aggregates, not a last-frame sample. */
    u32 a_prims = 0, a_hidden = 0, a_slotg = 0, a_slothid = 0, a_sciov = 0;
#endif

    while (1) {
        /* Canvas background: #0a0e1a in flat-shaded full-range RGB. */
        gsKit_clear(gs, GS_SETREG_RGBAQ(0x0a, 0x0e, 0x1a, 0x80, 0x00));
#ifdef PS2UI_SAMPLE_TELEMETRY
        {
            u32 t0 = cop0_count(), dt;
            ps2ui_render(&ui, gs);
            dt = cop0_count() - t0;
            if (dt < t_min) t_min = dt;
            if (dt > t_max) t_max = dt;
            t_sum += dt;
        }
#else
        ps2ui_render(&ui, gs);
#endif
        gsKit_queue_exec(gs);
        gsKit_sync_flip(gs);
#ifdef PS2UI_SAMPLE_TELEMETRY
        {
            /* Wall time of the whole loop, vsync included: more than
             * one field's worth of cycles means the flip missed. */
            u32 now = cop0_count(), loop = now - t_frame_prev;
            if (loop > EE_HZ / 60u + EE_HZ / 600u)
                missed++;
            elapsed += loop;
            t_frame_prev = now;
            sec_frames++;

            /* Peaks for the budgeting numbers, a sum for the alarm:
             * one overflowed frame in the interval must be visible. */
            if (ui.stats.prims > a_prims) a_prims = ui.stats.prims;
            if (ui.stats.skipped_hidden > a_hidden) a_hidden = ui.stats.skipped_hidden;
            if (ui.stats.slot_glyphs > a_slotg) a_slotg = ui.stats.slot_glyphs;
            if (ui.stats.slots_hidden > a_slothid) a_slothid = ui.stats.slots_hidden;
            a_sciov += ui.stats.scissor_overflow;

            /* Report on elapsed time, so the line is a real second at
             * any frame rate rather than 60 frames however long those
             * took. */
            if (elapsed >= EE_HZ) {
                u32 fps10 = (u32)(((u64)sec_frames * 10u * EE_HZ + elapsed / 2u)
                                  / elapsed);
                printf("ps2ui-telemetry frame=%u fps=%u.%u miss=%u "
                       "ee_us(min/avg/max)=%u/%u/%u "
                       "prims=%u hidden=%u slotg=%u slothid=%u sciov=%u\n",
                       frame, fps10 / 10u, fps10 % 10u, missed,
                       t_min / (EE_HZ / 1000000u),
                       (t_sum / sec_frames) / (EE_HZ / 1000000u),
                       t_max / (EE_HZ / 1000000u),
                       a_prims, a_hidden, a_slotg, a_slothid, a_sciov);
                t_min = 0xFFFFFFFFu; t_max = 0; t_sum = 0;
                sec_frames = 0; missed = 0; elapsed = 0;
                a_prims = 0; a_hidden = 0; a_slotg = 0;
                a_slothid = 0; a_sciov = 0;
            }
        }
#endif

        /* Walk every focus state so a timed screenshot sweep sees each
         * one: hold, then move right (wrapping via down) through the
         * graph; when movement dead-ends, jump back to the initial. */
        frame++;
        if (PS2UI_SAMPLE_CYCLE && frame % FRAMES_PER_STATE == 0) {
            if (!ps2ui_move(&ui, PS2UI_RIGHT) && !ps2ui_move(&ui, PS2UI_DOWN))
                ui.focus = ui.hdr->initial_focus;
        }
    }
    return 0;
}
