/* The step 6 probe's pattern, in a header of its own so the host test
 * suite can compile the exact bits the console draws. The instrument's
 * previous pattern was a periodic checker, and the periodicity is what
 * voided it twice at a bench: a texture-stride fault shifts row y's
 * texels by a multiple of 64, every multiple of 64 is a multiple of the
 * checker's 16-texel period, and so the one fault class the wide-atlas
 * column existed to catch rendered as a perfectly clean column. An
 * instrument blind to its own hypothesis is worse than no instrument.
 *
 * The replacement is aperiodic vertical bars: 64 cells of 4 texels
 * across a 256-texel row, one bit per cell, from the constant below.
 * The properties that make it an instrument are pinned by
 * test_runtime.c against these exact bits, not asserted here in prose:
 *
 *   - every 16-cell window disagrees with its own image at EVERY cell
 *     shift 1..31 in at least 4 of 16 cells, so no texel shift that is
 *     a whole number of cells can render as alignment -- including 64
 *     (a TBW unit) and the 4..12-texel DMA-truncation class;
 *   - every 16-cell window carries at least 7 bar transitions, so a
 *     sub-cell shift always has edges to read at the seam (the
 *     alignment card proved the bench resolves 1px);
 *   - the ON share is 38/64, deliberately off 50%: column G renders ON
 *     and OFF cells from CLUT indices the CSM1 permutation exchanges,
 *     so a wrong CLUT convention swaps the two colours' AREAS and the
 *     capture's colour fingerprint flips -- readable by a machine,
 *     which is what makes G a CI instrument and not only a bench one.
 *
 * Bars run vertically so continuity across the horizontal band seam is
 * a vernier reading, the sharpest comparison an eye can make -- and so
 * a stride fault, which shifts each ROW differently, breaks the bars
 * into a staircase that needs no reference band at all. Bars carry no
 * vertical information, so one horizontal stripe (rows P6_STRIPE_Y0
 * onward, forced ON) is the V axis: a vertical sampling shift moves it
 * against the reference band's copy. */

#ifndef PROBE6_PATTERN_H
#define PROBE6_PATTERN_H

/* Cell c is ON iff bit c is set. Generated by randomized search over
 * the three pinned properties; there is nothing meaningful about the
 * value beyond satisfying them, and any replacement must re-pass the
 * test suite's pins. */
#define P6_PATTERN_BITS 0xD9BAC2B3D6AF69E5ull

#define P6_PAT_CELLS   64   /* bits in the constant */
#define P6_CELL        4    /* texels per cell */
#define P6_STRIPE_Y0   20   /* the horizontal stripe: rows [Y0, Y0+H) */
#define P6_STRIPE_H    4

static inline int p6_bar(int x)
{
    return (int)((P6_PATTERN_BITS >> ((x / P6_CELL) & 63)) & 1u);
}

/* The full pattern: bars everywhere, stripe rows forced ON. Both bands
 * of every column sample this same function, phase-shifted by the
 * column's own UV origin. */
static inline int p6_on(int x, int y)
{
    if (y >= P6_STRIPE_Y0 && y < P6_STRIPE_Y0 + P6_STRIPE_H)
        return 1;
    return p6_bar(x);
}

#endif /* PROBE6_PATTERN_H */
