#!/bin/sh
# Embed the console's IOP modules into the ELF.
#
#   sh embed_irx.sh <outdir> <module> [<module> ...]
#
# Unlike runtime/sample/embed_irx.sh, this one does not pick between
# stacks: the console needs the BDM stack, exFAT and all, and a PS2SDK
# without it cannot build a console that reads an exFAT HDD. So a
# missing module FAILS THE BUILD, naming the module, rather than
# linking an ELF that would boot to the purple screen at a bench.
#
# One generated .c holding every module, for the reason the sample's
# script gives: a per-module file list cannot be discovered by the same
# make pass that generates it.
set -e
out="$1"; shift
irx="${PS2SDK}/iop/irx"
bin2c="${PS2SDK}/bin/bin2c"

for m in "$@"; do
    if [ ! -f "$irx/$m.irx" ]; then
        echo "embed_irx: $irx/$m.irx is missing; this PS2SDK cannot build the console" >&2
        exit 1
    fi
done

{
    echo '/* Generated by console/embed_irx.sh. Do not edit. */'
    echo '#include "irx_table.h"'
    echo
} > "$out/irx_table.c"

for m in "$@"; do
    "$bin2c" "$irx/$m.irx" "$out/irx_tmp_$m.c" "irx_$m"
    cat "$out/irx_tmp_$m.c" >> "$out/irx_table.c"
    rm -f "$out/irx_tmp_$m.c"
done

{
    echo
    echo "const irx_module irx_modules[] = {"
    for m in "$@"; do
        echo "    { \"$m\", irx_$m, &size_irx_$m },"
    done
    echo "};"
    echo "const int n_irx_modules = sizeof irx_modules / sizeof irx_modules[0];"
} >> "$out/irx_table.c"

cat > "$out/irx_table.h" <<'HDR'
/* Generated by console/embed_irx.sh. Do not edit. */
#ifndef CONSOLE_IRX_TABLE_H
#define CONSOLE_IRX_TABLE_H

typedef struct irx_module {
    const char *name;
    const unsigned char *data;
    const unsigned int *size;
} irx_module;

extern const irx_module irx_modules[];
extern const int n_irx_modules;

#endif
HDR

echo "embed_irx: $# modules: $*" >&2
