/* The OPHTML console core: one include for a launcher built on it.
 *
 * This is the public surface of libophtml-console.a -- the reusable
 * launcher machinery, with no UI and no main of its own:
 *
 *   library.h   the game model, title-ID parsing, the Neutrino
 *               command-line builder, the console_settings struct, the
 *               resolver seam, and OPL CFG mapping (portable C99).
 *   scan.h      walking a drive for games, OPL's DVD/ and CD/ layout.
 *   storage.h   bringing up the IOP storage modules (PS2-only).
 *   launch.h    handing a game to Neutrino (PS2-only).
 *   resolver.h  the default resolver: read a game's OPL CFG file.
 *   state.h     persist last-played and the launch breadcrumb to a
 *               memory card (PS2-only I/O; pure parse/format is in
 *               library.h).
 *
 * A downstream launcher links the archive and supplies the three
 * things it does NOT contain:
 *
 *   - a `main`: bring up the GS, choose and upload a theme, poll the
 *     pad, and drive the list (the OPHTML console's own main.c is one
 *     such consumer, not part of the library);
 *   - a theme blob and the ps2ui runtime it draws through
 *     (`ps2ui vendor-runtime` writes the runtime into a project);
 *   - the IOP module table storage.c resolves by name at run time,
 *     generated by THIS tree's console/embed_irx.sh (it defines
 *     `irx_modules`/`n_irx_modules` to the `irx_table.h` layout the
 *     archived storage.o was compiled against). Pass console/Makefile's
 *     `IRX =` list; the mandatory subset is iomanX, fileXio, sio2man,
 *     mcman, mcserv, freepad, bdm and bdmfs_fatfs -- a missing one does
 *     not fail the link, it holds the console on a grey screen. The
 *     modules are PS2SDK-version-specific, which is why the archive
 *     does not carry them.
 *
 * See console/README.md ("Building a launcher on the core") for the
 * full link recipe.
 */

#ifndef OPHTML_CONSOLE_H
#define OPHTML_CONSOLE_H

#include "library.h"
#include "scan.h"
#include "storage.h"
#include "launch.h"
#include "resolver.h"
#include "state.h"

#endif /* OPHTML_CONSOLE_H */
